import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import Link from "next/link";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Welcome to The Universe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

     <body className={`${roboto.className} min-h-full`}>
  <header className="fixed top-0 left-0 z-50 flex w-full items-center justify-between bg-black/70 px-8 py-4 backdrop-blur">
  
  

  <nav className="flex gap-8 text-white font-medium">
    <Link href="/" className="hover:text-cyan-400 transition">
      Home
    </Link>

    <Link href="/about" className="hover:text-cyan-400 transition">
      About
    </Link>

    <Link href="/contact" className="hover:text-cyan-400 transition">
      Contact
    </Link>
  </nav>
</header>
  {children}
</body>
    </html>
  );
}
